### ISSUE TITLE
lstm and lstm rezoom not working

### ISSUE THREAD

**Issue by manojgeorge** [Russell91/TensorBox#83]
overfeat and overfeat rezoom works fine, but I am having issues when I try to use the reinspect algorithm. The full stack trace is below. I am using CPU to simplify things, the same error also occurs with GPU. I am using the base install (ie no changes to lstm.json or lstm_rezoom.json) files.

I have gone through train.py line by line and does not see an issue. Also, I installed tensorflow from source. 

The error I see is Expected size[1] in [0, 500], but got 1000 (full trace below). If I change the lstm_size parameter in the json file, the error message changes (expected size seems to be always double the lstm_size). 

Will keep looking at the code, but wondering if anyone else has seen this issue.

python train.py --hypes hypes/lstm_rezoom.json  --logdir output
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: 10021.localdomain
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: 10021.localdomain
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: 367.48.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.48  Sat Sep  3 18:21:08 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.48.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:293] kernel version seems to match DSO: 367.48.0
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7fa949a6d310>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7fa932a03450>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 491, in train
    ], feed_dict=lr_feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Expected size[1] in [0, 500], but got 1000
	 [[Node: decoder/RNN/MultiRNNCell/Cell0/Slice = Slice[Index=DT_INT32, T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](decoder/zeros, decoder/RNN/MultiRNNCell/Cell0/Slice/begin, decoder/RNN/MultiRNNCell/Cell0/Slice/size)]]

Caused by op u'decoder/RNN/MultiRNNCell/Cell0/Slice', defined at:
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 336, in build
    boxes_loss[phase]) = build_forward_backward(H, x, encoder_net, phase, boxes, flags)
  File "train.py", line 235, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, googlenet, phase, reuse)
  File "train.py", line 157, in build_forward
    lstm_outputs = build_lstm_inner(H, lstm_input)
  File "train.py", line 45, in build_lstm_inner
    output, state = lstm(lstm_input, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 813, in __call__
    state, [0, cur_state_pos], [-1, cell.state_size])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 430, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2248, in _slice
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2388, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1300, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Expected size[1] in [0, 500], but got 1000
	 [[Node: decoder/RNN/MultiRNNCell/Cell0/Slice = Slice[Index=DT_INT32, T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](decoder/zeros, decoder/RNN/MultiRNNCell/Cell0/Slice/begin, decoder/RNN/MultiRNNCell/Cell0/Slice/size)]]

**Comment by Russell91** [comment]
Can you confirm that you are using Tensorflow 0.10 or greater? Unfortunately, the google guys are constantly changing APIs and breaking things for us. It's been particularly bad the last 2 months, but I am hoping it will get better.

**Comment by manojgeorge** [comment]
Thank you Russell and sorry to hear about the API changes. I ran:
pip list | grep tensorflow
and I get tensorflow (0.10.0)

Re-installed everything this morning, as a part of the trouble shooting effort. I am looking at the error stack also, should I try an earlier version of tensorflow? Or move up to r11?

I don't mind re-installing again if I need to.

**Comment by Russell91** [comment]
Can you reclone the repository and check?

**Comment by manojgeorge** [comment]
Ok great working now. I also upgraded to r0.11. Did you make any changes, just curious.

**Comment by manojgeorge** [comment]
Great job by the way! It is a great place to start for someone starting up on image segmentation. Super easy to change to a different data set also.

**Comment by Russell91** [comment]
Cool. I made a mistake a few days ago when upgrading to 0.10 support.
That's why it works now!
